//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.21 at 06:47:38 PM EAT 
//
package com.namaraka.recon.config.v1_0;

import com.namaraka.recon.utilities.XMLObject;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="conntimeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="readtimeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxtotalconnections" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="integrationthreadwait" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="dbmsthreadwait" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="passwordlength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="connectionsperroute" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="emailalerts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="turnon" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fetchsize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dbmslayerip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="schedulers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="retryfailed" type="{https://namaraka.com/bizlogic/config/v1_0}schedulertype"/>
 *                   &lt;element name="pickpending" type="{https://namaraka.com/bizlogic/config/v1_0}schedulertype"/>
 *                   &lt;element name="checkpersitentfailed" type="{https://namaraka.com/bizlogic/config/v1_0}schedulertype"/>
 *                   &lt;element name="handshakesession" type="{https://namaraka.com/bizlogic/config/v1_0}schedulertype"/>
 *                   &lt;element name="beneficiarysession" type="{https://namaraka.com/bizlogic/config/v1_0}schedulertype"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="managermethods">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="save" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="read" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="update" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="delete" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="handshake" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nodenames">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="servicerequest" type="{https://namaraka.com/bizlogic/config/v1_0}min2String"/>
 *                   &lt;element name="paymentrequest" type="{https://namaraka.com/bizlogic/config/v1_0}min2String"/>
 *                   &lt;element name="apiclient" type="{https://namaraka.com/bizlogic/config/v1_0}min2String"/>
 *                   &lt;element name="beneficiarydetailsrequest" type="{https://namaraka.com/bizlogic/config/v1_0}min2String"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="internalmethods">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="updatestatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fetchtransaction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="integrationmethods">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="makepayment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="maketransfer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allowedips">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="hash">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="pbkdf2_iteration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="saltbytesize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="hashbytesize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {})
@XmlRootElement(name = "appconfig")
public class Appconfig implements XMLObject {

    protected int conntimeout;
    protected int readtimeout;
    protected int maxtotalconnections;
    protected long integrationthreadwait;
    protected long dbmsthreadwait;
    protected int passwordlength;
    protected int connectionsperroute;
    @XmlElement(required = true)
    protected String emailalerts;
    @XmlElement(required = true)
    protected String turnon;
    protected int serviceid;
    protected int fetchsize;
    @XmlElement(required = true)
    protected String dbmslayerip;
    @XmlElement(required = true)
    protected Appconfig.Schedulers schedulers;
    @XmlElement(required = true)
    protected Appconfig.Managermethods managermethods;
    @XmlElement(required = true)
    protected Appconfig.Nodenames nodenames;
    @XmlElement(required = true)
    protected Appconfig.Internalmethods internalmethods;
    @XmlElement(required = true)
    protected Appconfig.Integrationmethods integrationmethods;
    @XmlElement(required = true)
    protected Appconfig.Allowedips allowedips;
    @XmlElement(required = true)
    protected Appconfig.Hash hash;
    @XmlElement(required = true)
    protected Appconfig.Configfiles configfiles;

    /**
     * Gets the value of the configfiles property.
     *
     * @return possible object is {@link Appconfig.Configfiles }
     *
     */
    public Appconfig.Configfiles getConfigfiles() {
        return configfiles;
    }

    /**
     * Sets the value of the configfiles property.
     *
     * @param value allowed object is {@link Appconfig.Configfiles }
     *
     */
    public void setConfigfiles(Appconfig.Configfiles value) {
        this.configfiles = value;
    }

    /**
     * Gets the value of the conntimeout property.
     *
     */
    public int getConntimeout() {
        return conntimeout;
    }

    /**
     * Sets the value of the conntimeout property.
     *
     */
    public void setConntimeout(int value) {
        this.conntimeout = value;
    }

    /**
     * Gets the value of the readtimeout property.
     *
     */
    public int getReadtimeout() {
        return readtimeout;
    }

    /**
     * Sets the value of the readtimeout property.
     *
     */
    public void setReadtimeout(int value) {
        this.readtimeout = value;
    }

    /**
     * Gets the value of the maxtotalconnections property.
     *
     */
    public int getMaxtotalconnections() {
        return maxtotalconnections;
    }

    /**
     * Sets the value of the maxtotalconnections property.
     *
     */
    public void setMaxtotalconnections(int value) {
        this.maxtotalconnections = value;
    }

    /**
     * Gets the value of the integrationthreadwait property.
     *
     */
    public long getIntegrationthreadwait() {
        return integrationthreadwait;
    }

    /**
     * Sets the value of the integrationthreadwait property.
     *
     */
    public void setIntegrationthreadwait(long value) {
        this.integrationthreadwait = value;
    }

    /**
     * Gets the value of the dbmsthreadwait property.
     *
     */
    public long getDbmsthreadwait() {
        return dbmsthreadwait;
    }

    /**
     * Sets the value of the dbmsthreadwait property.
     *
     */
    public void setDbmsthreadwait(long value) {
        this.dbmsthreadwait = value;
    }

    /**
     * Gets the value of the passwordlength property.
     *
     */
    public int getPasswordlength() {
        return passwordlength;
    }

    /**
     * Sets the value of the passwordlength property.
     *
     */
    public void setPasswordlength(int value) {
        this.passwordlength = value;
    }

    /**
     * Gets the value of the connectionsperroute property.
     *
     */
    public int getConnectionsperroute() {
        return connectionsperroute;
    }

    /**
     * Sets the value of the connectionsperroute property.
     *
     */
    public void setConnectionsperroute(int value) {
        this.connectionsperroute = value;
    }

    /**
     * Gets the value of the emailalerts property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEmailalerts() {
        return emailalerts;
    }

    /**
     * Sets the value of the emailalerts property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setEmailalerts(String value) {
        this.emailalerts = value;
    }

    /**
     * Gets the value of the turnon property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTurnon() {
        return turnon;
    }

    /**
     * Sets the value of the turnon property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTurnon(String value) {
        this.turnon = value;
    }

    /**
     * Gets the value of the serviceid property.
     *
     */
    public int getServiceid() {
        return serviceid;
    }

    /**
     * Sets the value of the serviceid property.
     *
     */
    public void setServiceid(int value) {
        this.serviceid = value;
    }

    /**
     * Gets the value of the fetchsize property.
     *
     */
    public int getFetchsize() {
        return fetchsize;
    }

    /**
     * Sets the value of the fetchsize property.
     *
     */
    public void setFetchsize(int value) {
        this.fetchsize = value;
    }

    /**
     * Gets the value of the dbmslayerip property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDbmslayerip() {
        return dbmslayerip;
    }

    /**
     * Sets the value of the dbmslayerip property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDbmslayerip(String value) {
        this.dbmslayerip = value;
    }

    /**
     * Gets the value of the schedulers property.
     *
     * @return possible object is {@link Appconfig.Schedulers }
     *
     */
    public Appconfig.Schedulers getSchedulers() {
        return schedulers;
    }

    /**
     * Sets the value of the schedulers property.
     *
     * @param value allowed object is {@link Appconfig.Schedulers }
     *
     */
    public void setSchedulers(Appconfig.Schedulers value) {
        this.schedulers = value;
    }

    /**
     * Gets the value of the managermethods property.
     *
     * @return possible object is {@link Appconfig.Managermethods }
     *
     */
    public Appconfig.Managermethods getManagermethods() {
        return managermethods;
    }

    /**
     * Sets the value of the managermethods property.
     *
     * @param value allowed object is {@link Appconfig.Managermethods }
     *
     */
    public void setManagermethods(Appconfig.Managermethods value) {
        this.managermethods = value;
    }

    /**
     * Gets the value of the nodenames property.
     *
     * @return possible object is {@link Appconfig.Nodenames }
     *
     */
    public Appconfig.Nodenames getNodenames() {
        return nodenames;
    }

    /**
     * Sets the value of the nodenames property.
     *
     * @param value allowed object is {@link Appconfig.Nodenames }
     *
     */
    public void setNodenames(Appconfig.Nodenames value) {
        this.nodenames = value;
    }

    /**
     * Gets the value of the internalmethods property.
     *
     * @return possible object is {@link Appconfig.Internalmethods }
     *
     */
    public Appconfig.Internalmethods getInternalmethods() {
        return internalmethods;
    }

    /**
     * Sets the value of the internalmethods property.
     *
     * @param value allowed object is {@link Appconfig.Internalmethods }
     *
     */
    public void setInternalmethods(Appconfig.Internalmethods value) {
        this.internalmethods = value;
    }

    /**
     * Gets the value of the integrationmethods property.
     *
     * @return possible object is {@link Appconfig.Integrationmethods }
     *
     */
    public Appconfig.Integrationmethods getIntegrationmethods() {
        return integrationmethods;
    }

    /**
     * Sets the value of the integrationmethods property.
     *
     * @param value allowed object is {@link Appconfig.Integrationmethods }
     *
     */
    public void setIntegrationmethods(Appconfig.Integrationmethods value) {
        this.integrationmethods = value;
    }

    /**
     * Gets the value of the allowedips property.
     *
     * @return possible object is {@link Appconfig.Allowedips }
     *
     */
    public Appconfig.Allowedips getAllowedips() {
        return allowedips;
    }

    /**
     * Sets the value of the allowedips property.
     *
     * @param value allowed object is {@link Appconfig.Allowedips }
     *
     */
    public void setAllowedips(Appconfig.Allowedips value) {
        this.allowedips = value;
    }

    /**
     * Gets the value of the hash property.
     *
     * @return possible object is {@link Appconfig.Hash }
     *
     */
    public Appconfig.Hash getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     *
     * @param value allowed object is {@link Appconfig.Hash }
     *
     */
    public void setHash(Appconfig.Hash value) {
        this.hash = value;
    }

    @Override
    public XMLObject getXMLObject() {
        return this;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ip"
    })
    public static class Allowedips {

        @XmlElement(required = true)
        protected List<String> ip;

        /**
         * Gets the value of the ip property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the ip property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIp().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         *
         *
         */
        public List<String> getIp() {
            if (ip == null) {
                ip = new ArrayList<String>();
            }
            return this.ip;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="pbkdf2_iteration" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="saltbytesize" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="hashbytesize" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {})
    public static class Hash {

        @XmlElement(name = "pbkdf2_iteration")
        protected int pbkdf2Iteration;
        protected int saltbytesize;
        protected int hashbytesize;

        /**
         * Gets the value of the pbkdf2Iteration property.
         *
         */
        public int getPbkdf2Iteration() {
            return pbkdf2Iteration;
        }

        /**
         * Sets the value of the pbkdf2Iteration property.
         *
         */
        public void setPbkdf2Iteration(int value) {
            this.pbkdf2Iteration = value;
        }

        /**
         * Gets the value of the saltbytesize property.
         *
         */
        public int getSaltbytesize() {
            return saltbytesize;
        }

        /**
         * Sets the value of the saltbytesize property.
         *
         */
        public void setSaltbytesize(int value) {
            this.saltbytesize = value;
        }

        /**
         * Gets the value of the hashbytesize property.
         *
         */
        public int getHashbytesize() {
            return hashbytesize;
        }

        /**
         * Sets the value of the hashbytesize property.
         *
         */
        public void setHashbytesize(int value) {
            this.hashbytesize = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="makepayment" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="maketransfer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {})
    public static class Integrationmethods {

        @XmlElement(required = true)
        protected String makepayment;
        @XmlElement(required = true)
        protected String maketransfer;

        /**
         * Gets the value of the makepayment property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getMakepayment() {
            return makepayment;
        }

        /**
         * Sets the value of the makepayment property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setMakepayment(String value) {
            this.makepayment = value;
        }

        /**
         * Gets the value of the maketransfer property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getMaketransfer() {
            return maketransfer;
        }

        /**
         * Sets the value of the maketransfer property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setMaketransfer(String value) {
            this.maketransfer = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="updatestatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fetchtransaction" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {})
    public static class Internalmethods {

        @XmlElement(required = true)
        protected String updatestatus;
        @XmlElement(required = true)
        protected String fetchtransaction;

        /**
         * Gets the value of the updatestatus property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getUpdatestatus() {
            return updatestatus;
        }

        /**
         * Sets the value of the updatestatus property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setUpdatestatus(String value) {
            this.updatestatus = value;
        }

        /**
         * Gets the value of the fetchtransaction property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getFetchtransaction() {
            return fetchtransaction;
        }

        /**
         * Sets the value of the fetchtransaction property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setFetchtransaction(String value) {
            this.fetchtransaction = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="save" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="read" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="update" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="delete" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="handshake" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {})
    public static class Managermethods {

        @XmlElement(required = true)
        protected String save;
        @XmlElement(required = true)
        protected String read;
        @XmlElement(required = true)
        protected String update;
        @XmlElement(required = true)
        protected String delete;
        @XmlElement(required = true)
        protected String handshake;

        /**
         * Gets the value of the save property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getSave() {
            return save;
        }

        /**
         * Sets the value of the save property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setSave(String value) {
            this.save = value;
        }

        /**
         * Gets the value of the read property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getRead() {
            return read;
        }

        /**
         * Sets the value of the read property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setRead(String value) {
            this.read = value;
        }

        /**
         * Gets the value of the update property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getUpdate() {
            return update;
        }

        /**
         * Sets the value of the update property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setUpdate(String value) {
            this.update = value;
        }

        /**
         * Gets the value of the delete property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getDelete() {
            return delete;
        }

        /**
         * Sets the value of the delete property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setDelete(String value) {
            this.delete = value;
        }

        /**
         * Gets the value of the handshake property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getHandshake() {
            return handshake;
        }

        /**
         * Sets the value of the handshake property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setHandshake(String value) {
            this.handshake = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="servicerequest" type="{https://namaraka.com/bizlogic/config/v1_0}min2String"/>
     *         &lt;element name="paymentrequest" type="{https://namaraka.com/bizlogic/config/v1_0}min2String"/>
     *         &lt;element name="apiclient" type="{https://namaraka.com/bizlogic/config/v1_0}min2String"/>
     *         &lt;element name="beneficiarydetailsrequest" type="{https://namaraka.com/bizlogic/config/v1_0}min2String"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {})
    public static class Nodenames {

        @XmlElement(required = true)
        protected String servicerequest;
        @XmlElement(required = true)
        protected String paymentrequest;
        @XmlElement(required = true)
        protected String apiclient;
        @XmlElement(required = true)
        protected String beneficiarydetailsrequest;

        /**
         * Gets the value of the servicerequest property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getServicerequest() {
            return servicerequest;
        }

        /**
         * Sets the value of the servicerequest property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setServicerequest(String value) {
            this.servicerequest = value;
        }

        /**
         * Gets the value of the paymentrequest property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getPaymentrequest() {
            return paymentrequest;
        }

        /**
         * Sets the value of the paymentrequest property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setPaymentrequest(String value) {
            this.paymentrequest = value;
        }

        /**
         * Gets the value of the apiclient property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getApiclient() {
            return apiclient;
        }

        /**
         * Sets the value of the apiclient property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setApiclient(String value) {
            this.apiclient = value;
        }

        /**
         * Gets the value of the beneficiarydetailsrequest property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getBeneficiarydetailsrequest() {
            return beneficiarydetailsrequest;
        }

        /**
         * Sets the value of the beneficiarydetailsrequest property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setBeneficiarydetailsrequest(String value) {
            this.beneficiarydetailsrequest = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="retryfailed" type="{https://namaraka.com/bizlogic/config/v1_0}schedulertype"/>
     *         &lt;element name="pickpending" type="{https://namaraka.com/bizlogic/config/v1_0}schedulertype"/>
     *         &lt;element name="checkpersitentfailed" type="{https://namaraka.com/bizlogic/config/v1_0}schedulertype"/>
     *         &lt;element name="handshakesession" type="{https://namaraka.com/bizlogic/config/v1_0}schedulertype"/>
     *         &lt;element name="beneficiarysession" type="{https://namaraka.com/bizlogic/config/v1_0}schedulertype"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {})
    public static class Schedulers {

        @XmlElement(required = true)
        protected Schedulertype retryfailed;
        @XmlElement(required = true)
        protected Schedulertype pickpending;
        @XmlElement(required = true)
        protected Schedulertype checkpersitentfailed;
        @XmlElement(required = true)
        protected Schedulertype handshakesession;
        @XmlElement(required = true)
        protected Schedulertype beneficiarysession;

        /**
         * Gets the value of the retryfailed property.
         *
         * @return possible object is {@link Schedulertype }
         *
         */
        public Schedulertype getRetryfailed() {
            return retryfailed;
        }

        /**
         * Sets the value of the retryfailed property.
         *
         * @param value allowed object is {@link Schedulertype }
         *
         */
        public void setRetryfailed(Schedulertype value) {
            this.retryfailed = value;
        }

        /**
         * Gets the value of the pickpending property.
         *
         * @return possible object is {@link Schedulertype }
         *
         */
        public Schedulertype getPickpending() {
            return pickpending;
        }

        /**
         * Sets the value of the pickpending property.
         *
         * @param value allowed object is {@link Schedulertype }
         *
         */
        public void setPickpending(Schedulertype value) {
            this.pickpending = value;
        }

        /**
         * Gets the value of the checkpersitentfailed property.
         *
         * @return possible object is {@link Schedulertype }
         *
         */
        public Schedulertype getCheckpersitentfailed() {
            return checkpersitentfailed;
        }

        /**
         * Sets the value of the checkpersitentfailed property.
         *
         * @param value allowed object is {@link Schedulertype }
         *
         */
        public void setCheckpersitentfailed(Schedulertype value) {
            this.checkpersitentfailed = value;
        }

        /**
         * Gets the value of the handshakesession property.
         *
         * @return possible object is {@link Schedulertype }
         *
         */
        public Schedulertype getHandshakesession() {
            return handshakesession;
        }

        /**
         * Sets the value of the handshakesession property.
         *
         * @param value allowed object is {@link Schedulertype }
         *
         */
        public void setHandshakesession(Schedulertype value) {
            this.handshakesession = value;
        }

        /**
         * Gets the value of the beneficiarysession property.
         *
         * @return possible object is {@link Schedulertype }
         *
         */
        public Schedulertype getBeneficiarysession() {
            return beneficiarysession;
        }

        /**
         * Sets the value of the beneficiarysession property.
         *
         * @param value allowed object is {@link Schedulertype }
         *
         */
        public void setBeneficiarysession(Schedulertype value) {
            this.beneficiarysession = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element name="log4jprops" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="hibernateprops" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="hibernatecustomtypes" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="xsdfoldername" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {})
    public static class Configfiles {

        @XmlElement(name = "log4jprops", required = true)
        protected String log4Jprops;
        @XmlElement(required = true)
        protected String hibernateprops;
        @XmlElement(required = true)
        protected String hibernatecustomtypes;
        @XmlElement(required = true)
        protected String xsdfoldername;

        /**
         * Gets the value of the log4Jprops property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getLog4Jprops() {
            return log4Jprops;
        }

        /**
         * Sets the value of the log4Jprops property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setLog4Jprops(String value) {
            this.log4Jprops = value;
        }

        /**
         * Gets the value of the hibernateprops property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getHibernateprops() {
            return hibernateprops;
        }

        /**
         * Sets the value of the hibernateprops property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setHibernateprops(String value) {
            this.hibernateprops = value;
        }

        /**
         * Gets the value of the hibernatecustomtypes property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getHibernatecustomtypes() {
            return hibernatecustomtypes;
        }

        /**
         * Sets the value of the hibernatecustomtypes property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setHibernatecustomtypes(String value) {
            this.hibernatecustomtypes = value;
        }

        /**
         * Gets the value of the xsdfoldername property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getXsdfoldername() {
            return xsdfoldername;
        }

        /**
         * Sets the value of the xsdfoldername property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setXsdfoldername(String value) {
            this.xsdfoldername = value;
        }

    }

}
